student/config/routes.rb
Rails.application.routes.draw do
  resources :teachers

  root 'welcome#new'

  resources :containers
  resources :studentinfos do
    collection do
      get :selectstudent
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

student/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

student/app/models/container.rb
class Container < ApplicationRecord
  has_many :studentinfos, dependent: :destroy
  has_many :teachers, dependent: :destroy
end

student/app/models/studentinfo.rb
class Studentinfo < ApplicationRecord
  belongs_to :container
  
end

student/app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :container
end

student/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

student/app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  def new
    @container = Container.new
  end

  def create
    @container = Container.new(container_parpams)
    @container.save
    redirect_to @container
  end

  def show
    @container = Container.find(params[:id])
    @students = @container.studentinfos
    @teachers = @container.teachers
  end

  def index
    @containers = Container.all
    
  end

  def edit
    @container = Container.find(params[:id])
  end

  def update
    @container = Container.find(params[:id])
    if @container.update(container_parpams)
      redirect_to @container
    else
      render 'edit'
    end
  end

  def destroy
    @container = Container.find(params[:id])
    @container.destroy
    redirect_to containers_path
  end

  private
    def container_parpams
      params.require(:container).permit(:name)
    end
end

student/app/controllers/studentinfos_controller.rb
class StudentinfosController < ApplicationController
  def new
    @student = Studentinfo.new
  end

  def create
    @student = Studentinfo.new(student_prams)
    @student.save
    redirect_to @student
  end

  def index
    @students = Studentinfo.all
  end

  def show
    @student = Studentinfo.find(params[:id])
    @container = Container.find(@student.container_id)
  end

  def edit
    @student = Studentinfo.find(params[:id])
  end

  def update
    @student = Studentinfo.find(params[:id])
    if @student.update(student_prams)
      redirect_to @student
    else
      render 'edit'
    end
  end

  def selectstudent
    con_id = 0 
    if ((con_id= params[:container_id].to_i) > 0)
      @container = Container.find(con_id)
      @student = @container.studentinfos.where(["name like ?","%#{params[:name]}%"])
    else
      @student = Studentinfo.where(["name like ?","%#{params[:name]}%"])
    end
  end

  def destroy
    @student = Studentinfo.find(params[:id])
    @student.destroy
    redirect_to studentinfos_path
  end

  private
    def student_prams
        params.require(:studentinfo).permit(:name, :gender, :container_id)
    end
end

student/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new
    @teacher = Teacher.new
  end
 
  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to @teacher
    else
      render 'new'
    end
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def index
    @teachers = Teacher.all
  end
  
  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    if @teacher.update(teacher_params)
      redirect_to @teacher
    else
      render 'edit'
    end
  end
 
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    redirect_to teachers_path
  end

  private
    def teacher_params
      params.require(:teacher).permit(:name, :gender, :container_id)
    end

end

student/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def new
  end
end

student/app/helpers/application_helper.rb
module ApplicationHelper
end

student/app/helpers/containers_helper.rb
module ContainersHelper
end

student/app/helpers/studentinfos_helper.rb
module StudentinfosHelper
end

student/app/helpers/teachers_helper.rb
module TeachersHelper
end

student/app/helpers/welcome_helper.rb
module WelcomeHelper
end

student/app/views/containers/_form.html.erb
<%= form_for @container do |f| %>
  <p>
    <%= f.label :名称 %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit '完成' %>
  </p>
<% end %>

student/app/views/containers/edit.html.erb
<%= render 'form'%>
<%= link_to '返回', containers_path %>

student/app/views/containers/index.html.erb
<div id="title"><h3>所有班级</h3></div>
<%= link_to '首页', root_path %>
<%= link_to '添加班级', new_container_path %>
<%= link_to '添加学生', new_studentinfo_path %>
<table id="ta">
  <tr id="trcolor">
    <td>名称</td>
    <td>操作</td>
  </tr>

  <% @containers.each do |container| %>
    <tr id="bgtr">
      <td><%= container.name %></td>
      <td><%= link_to '编辑', edit_container_path(container) %>
          <%= link_to '详情', container_path(container) %>
          <%= link_to '删除', container_path(container),
                      method: :delete, data: { confirm: '确认删除？'}%></td>
    </tr>
  <% end %>
</table>

student/app/views/containers/new.html.erb
<%= render 'form'%>
<%= link_to '返回', containers_path%>

student/app/views/containers/show.html.erb
<div id="title"><strong>班级信息</strong></div> 
<div id="spantop">
  <span>学生信息</span>

 <table id="ta">
    <tr id="trcolor">
      <td>姓名</td>
      <td>性别</td>
    </tr>
  <% @students.each do |student| %>
    <tr id="bgtr">
      <td><%= student.name %></td>
      <td><%= student.gender %></td>
    </tr>
  <% end %>
 </table>
</div>

<div id="spantop">
  <span>教师信息</span>
 <table id="ta">
   <tr id="trcolor">
     <td>姓名</td>
     <td>性别</td>
   </tr>
   <% @teachers.each do |teacher| %>
     <tr id="bgtr">
       <td><%= teacher.name %></td>
       <td><%= teacher.gender %></td>
     </tr>
   <% end %>
  </table>
</div>
<%= link_to '返回', containers_path%>

student/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

student/app/views/studentinfos/_form.html.erb
<%= form_for @student do |f| %>
  <p>
    <%= f.label :班级 %>
    <%= f.select :container_id, Container.all.collect { |p| [ p.name, p.id ] } %>
  </p>

  <p>
    <%= f.label :姓名 %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :性别 %><br>
    <%= f.text_field :gender %>
  </p>

  <p>
    <%= f.submit '完成' %>
  </p>
<% end %>

student/app/views/studentinfos/edit.html.erb
<%= render 'form'%>
<%= link_to '返回', studentinfos_path %>

student/app/views/studentinfos/index.html.erb
<div id="title"><h3>所有学生</h3></div>
  <%= link_to '首页', root_path %>
  <%= link_to '添加学生', new_studentinfo_path %>
  <%= link_to '添加班级', new_container_path %>
<table id="ta">
  <tr id="trcolor">
    <td>姓名</td>
    <td>性别</td>
    <td>操作</td>
  </tr>

  <% @students.each do |student| %>
    <tr id="bgtr">
      <td><%= student.name %></td>
      <td><%= student.gender %></td>
      <td><%= link_to '编辑', edit_studentinfo_path(student) %>
	  <%= link_to '详情', studentinfo_path(student) %>
          <%= link_to '删除', studentinfo_path(student),
                      method: :delete, data: { confirm: '确认删除？'}%></td>
    </tr>
  <% end %>
</table>

student/app/views/studentinfos/new.html.erb
<%= form_for @student do |f| %>
  <p>
    <%= f.label :班级 %>
    <%= f.select :container_id, Container.all.collect { |p| [ p.name, p.id ] } %>
  </p>

  <p>
    <%= f.label :姓名 %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :性别 %><br>
    <%= f.text_field :gender %>
  </p>

  <p>
    <%= f.submit '完成' %>
  </p>
<% end %>
<%= link_to '返回', containers_path%>

student/app/views/studentinfos/selectstudent.html.erb
<div id="title"><h3>查询学生</h3></div>
<%= link_to '首页', root_path %>
<%=form_tag selectstudent_studentinfos_path, method: :get do |f|%>
<%= text_field_tag 'name', value=params[:name] %>
<%if @container == nil%>
<%= select_tag "container_id", options_for_select(Container.all.map{|c|[c.name,c.id]}),include_blank: '请选择' %>
<% else%>
<%= select_tag "container_id", options_for_select(Container.all.map{|c|[c.name,c.id]}),include_blank: @container.name  %>
<% end %>
<%= submit_tag '查找', :id => 'look'%>
<% end %>
  <div id="studnetshow">
    <table id="ta">
      <tr id="trcolor">
        <td>姓名</td>
        <td>性别</td>
        <td>班级</td>
      </tr>
     <% @student.each do |student|%>
       <tr id="bgtr">
         <td><%= student.name %></td>
         <td><%= student.gender%></td>
         <td><%= student.container.name%></td>
       </tr>
     <% end%>
   </table>
   </div>

student/app/views/studentinfos/show.html.erb
<p>
  <strong>姓名</strong>
  <%= @student.name %>
</p>

<p>
  <strong>性别</strong>
  <%= @student.gender %>
</p>

<p>
  <strong>班级</strong>
  <%= @container.name %>
</p>

<%= link_to '返回', studentinfos_path%>

student/app/views/teachers/_form.html.erb
<%= form_for @teacher do |f| %>
  <p>
     <%= f.label :班级 %>
     <%= f.select :container_id, Container.all.collect { |p| [ p.name, p.id ] } %>
  </p>
  <p>
    <%= f.label :姓名 %>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :性别 %>
    <%= f.text_field :gender %>
  </p>
 
  <p>
    <%= f.submit '完成'%>
  </p>
<% end %>

student/app/views/teachers/edit.html.erb
<div id="title"><h3>修改教师信息</h3></div>
<%= render 'form'%>
<%= link_to '返回', teachers_path %>

student/app/views/teachers/index.html.erb
<div id='title'><h3 >教师信息</h3></div>
<%= link_to '首页', root_path %>
<a href="teachers/new"><button>录入教师</button></a>
<br/>
<table id='ta'>
  <tr id="trcolor">
    <td>姓名</td>
    <td>性别</td>
    <td>操作</td>
  </tr>
  <% @teachers.each do |teacher| %>
    <tr id="bgtr">
      <td><%= teacher.name %></td>
      <td><%= teacher.gender %></td>
      <td><%= link_to '编辑', edit_teacher_path(teacher)%>
      <%= link_to '详情', teacher_path(teacher)%>
      <%= link_to '删除', teacher_path(teacher),
                      method: :delete, data: { confirm: '确认删除？'}%></td>
    </tr>
  <% end %>
</table>

student/app/views/teachers/new.html.erb
<div id="title"><h3>教师添加</h3></div>
<%= render 'form'%>
<%= link_to '返回',:back %>

student/app/views/teachers/show.html.erb
<div id="title"><h3>教师信息</h3></div>
<div>
<p>
  <strong>姓名</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>性别</strong>
  <%= @teacher.gender %>
</p>

<p>
  <strong>所带班级</strong>
  <%= @teacher.container.name %>
</p>
<%= link_to '返回', teachers_path %>
</div>

student/app/views/welcome/new.html.erb
<script>
 function hide(){
 $("ul").slideToggle(); 
}
</script>
<div id="title"><h1>学生管理系统</h1></div>

<div class="dropdown" style="float:left;">
  <button class="dropbtn">菜单</button>
  <div class="dropdown-content" style="left:0;">
  <a href="#"><%= link_to '班级',  controller: 'containers' %></a>
  <a href="#"><%= link_to '查询', controller: 'studentinfos', action: 'selectstudent' %></a>
  <a href="#"><%= link_to '教师', controller: 'teachers'%></a>
  <a href="#"><%= link_to '学生', controller: 'studentinfos' %></a>
  </div>